#pragma once
#define WIFI_SSID "REPLACE_ME"
#define WIFI_PASS "REPLACE_ME"
#define SONOS_LIVING_ROOM_IP "REPLACE_ME"
#define SONOS_LIVING_ROOM_NAME "REPLACE_ME"
#define SONOS_MOVE_IP "REPLACE_ME"
#define SONOS_MOVE_NAME "REPLACE_ME"
#define SONOS_PORT 1400
#define SONOS_LIVING_ROOM_RINCON "REPLACE_ME"
#define SONOS_MOVE_RINCON "REPLACE_ME"
